//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_gellary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public Answers()
        {
            this.Date = DateTime.Now;
        }

        public int Id { get; set; }
        public int UserId { get; set; }
        public int PictureId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual PicturesWaiting PicturesWaiting { get; set; }
        public virtual Users Users { get; set; }
    }
}
