//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_gellary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EGalleryEntities : DbContext
    {
        public EGalleryEntities()
            : base("name=EGalleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommentsToImages> CommentsToImages { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<LikesToImages> LikesToImages { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Verification> Verification { get; set; }
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<PicturesWaiting> PicturesWaiting { get; set; }
    }
}
