//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_gellary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicturesWaiting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PicturesWaiting()
        {
            this.Answers = new HashSet<Answers>();
            this.DateUpload = DateTime.Now;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DateUpload { get; set; }
        public string Expansion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual Users Users { get; set; }
    }
    public enum Status
    {
        WAITING = 1,
        VIEW = 2,
        BLOCK = 3
    }

}
