//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_gellary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Verification
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        [Display(Name = "VerificationCodeName", ResourceType = typeof(Resources.Resource))]
        public string VerificationCode { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
